# Generated by Django 3.2.7 on 2021-09-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsewerQuestins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('type_questions', models.PositiveSmallIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ListAnswerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.ansewerquestins')),
                ('answer_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.questons')),
                ('answer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.answeruser')),
            ],
        ),
        migrations.AddField(
            model_name='answeruser',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.quiz'),
        ),
        migrations.AddField(
            model_name='ansewerquestins',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.questons'),
        ),
    ]
