# Generated by Django 3.2.7 on 2021-09-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_quiz_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeruser',
            old_name='user',
            new_name='id_user',
        ),
    ]
