# Generated by Django 3.2.7 on 2021-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_rename_user_answeruser_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listansweruser',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
    ]
